# Generated by Django 5.2.8 on 2025-11-25 10:23

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='video_file',
            field=models.ImageField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='shorts/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
